name: Project CI
on:
  pull_request: # all PRs
  push:
    branches:
    - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_DISTRIBUTION: "temurin"
  JAVA_VERSION: "25"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Compile project
        run: ./gradlew testClasses buildPlugin
      - name: Upload build output
        uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: |
            build/
            !build/reports/
          retention-days: 1
      - name: Upload build reports
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: build-reports
          path: build/reports/
          retention-days: 7

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Download build output
        uses: actions/download-artifact@v7
        with:
          name: build-output
          path: build/
      - name: Run JUnit
        run: ./gradlew test
      - name: Upload JUnit report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: junit-report
          path: build/reports/junit
          retention-days: 7
      - name: Upload Jacoco Coverage
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: jacoco-coverage-report
          path: build/reports/jacoco
          retention-days: 7

  verify:
    name: Plugin Verifier
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Download build output
        uses: actions/download-artifact@v7
        with:
          name: build-output
          path: build/
      - name: Run IntelliJ Plugin Verifier
        run: ./gradlew verifyPlugin
      - name: Upload verification reports
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: plugin-verifier-reports
          path: build/reports/pluginVerifier/
          retention-days: 7
